language: c

compiler:
  - gcc
  - clang

env:
  - BTYPE="BINARY=64"
  - BTYPE="BINARY=64 USE_OPENMP=1"
  - BTYPE="BINARY=64 INTERFACE64=1"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq gfortran

script: 
 - set -e
 - if [ "uname -m" == "x86_64" ]; then make QUIET_MAKE=1 TARGET=NEHALEM NUM_THREADS=32 $BTYPE; fi 
 - if [ "uname -m" == "x86_64" ]; then make -C test TARGET=NEHALEM NUM_THREADS=32 $BTYPE; fi
 - if [ "uname -m" == "x86_64" ]; then make -C ctest TARGET=NEHALEM NUM_THREADS=32 $BTYPE; fi
 - if [ "uname -m" == "x86_64" ]; then make -C utest TARGET=NEHALEM NUM_THREADS=32 $BTYPE; fi
 - if [ "uname -m" == "ppc64le" ]; then make QUIET_MAKE=1 TARGET=POWER8 NUM_THREADS=32 $BTYPE; fi
 - if [ "uname -m" == "ppc64le" ]; then make -C test TARGET=POWER8 NUM_THREADS=32 $BTYPE; fi
 - if [ "uname -m" == "ppc64le" ]; then make -C ctest TARGET=POWER8 NUM_THREADS=32 $BTYPE; fi
 - if [ "uname -m" == "ppc64le" ]; then make -C utest TARGET=POWER8 NUM_THREADS=32 $BTYPE; fi


# whitelist
branches:
  only:
    - master
    - develop
