language: c

compiler:
  - gcc
  - clang

env:
 - TARGET_BOX=LINUX64 BTYPE="BINARY=64"
 - TARGET_BOX=LINUX64 BTYPE="BINARY=64 USE_OPENMP=1"
 - TARGET_BOX=LINUX64 BTYPE="BINARY=64 INTERFACE64=1"
 - TARGET_BOX=WIN64 BTYPE="BINARY=64 HOSTCC=gcc CC=x86_64-w64-mingw32-gcc FC=x86_64-w64-mingw32-gfortran"

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq gfortran
 - if [[ $TARGET_BOX == "WIN64" ]]; then sudo apt-get install -qq binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 gfortran-mingw-w64-x86-64; fi


script: 
 - set -e
 - uname -m
 - uname -a
 - if [ $(uname -m) == "x86_64" ]; then make QUIET_MAKE=1 TARGET=NEHALEM NUM_THREADS=32 $BTYPE; fi 
 - if [ $TARGET_BOX == "LINUX_64" ] && [ $(uname -m) == "x86_64" ]; then make -C test TARGET=NEHALEM NUM_THREADS=32 $BTYPE; fi
 - if [ $TARGET_BOX == "LINUX_64" ] && [ $(uname -m) == "x86_64" ]; then make -C ctest TARGET=NEHALEM NUM_THREADS=32 $BTYPE; fi
 - if [ $TARGET_BOX == "LINUX_64" ] && [ $(uname -m) == "x86_64" ]; then make -C utest TARGET=NEHALEM NUM_THREADS=32 $BTYPE; fi
 - if [ $(uname -m) == "ppc64le" ]; then make QUIET_MAKE=1 TARGET=POWER8 NUM_THREADS=32 $BTYPE; fi
 - if [ $(uname -m) == "ppc64le" ]; then make -C test TARGET=POWER8 NUM_THREADS=32 $BTYPE; fi
 - if [ $(uname -m) == "ppc64le" ]; then make -C ctest TARGET=POWER8 NUM_THREADS=32 $BTYPE; fi
 - if [ $(uname -m) == "ppc64le" ]; then make -C utest TARGET=POWER8 NUM_THREADS=32 $BTYPE; fi


# whitelist
branches:
  only:
    - master
    - develop
